USE Master
GO
IF DB_ID('RH') IS NOT NULL
	BEGIN
		ALTER DATABASE RH SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
		DROP DATABASE RH
	END
GO
CREATE DATABASE RH
GO
USE RH
GO


DROP TABLE IF EXISTS Patient;
CREATE TABLE Patient (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
	PatientTlfNr NVARCHAR (8) NOT NULL
);

DROP TABLE IF EXISTS Doktor;
CREATE TABLE Doktor (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS Speciale;
CREATE TABLE Speciale (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL,
    DoktorId INT FOREIGN KEY REFERENCES Doktor(Id)
);

DROP TABLE IF EXISTS TilDeltDoktor;
CREATE TABLE TilDeltDoktor (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    PatientId INT FOREIGN KEY REFERENCES Patient(Id),
    SpecialeId INT FOREIGN KEY REFERENCES Speciale(Id)
);