USE Master
GO
IF DB_ID('RH') IS NOT NULL
	BEGIN
		ALTER DATABASE RH SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
		DROP DATABASE RH
	END
GO
CREATE DATABASE RH
GO
USE RH
GO

DROP DATABASE RH;

DROP TABLE IF EXISTS Patient;
CREATE TABLE Patient (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(255),
    LastName NVARCHAR(255),
);

DROP TABLE IF EXISTS Doktor;
CREATE TABLE Doktor (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(255),
    LastName NVARCHAR(255)
);

DROP TABLE IF EXISTS Speciale;
CREATE TABLE Speciale (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    [Name] NVARCHAR(255),
    DoktorId INT FOREIGN KEY REFERENCES Doktor(Id)
);

DROP TABLE IF EXISTS TilDeltDoktor;
CREATE TABLE TilDeltDoktor (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    PatientId INT FOREIGN KEY REFERENCES PatientId(Id),
    SpecialeId INT FOREIGN KEY REFERENCES SpecialeId(Id)
);